### ISSUE TITLE
关于HW1问题

### ISSUE THREAD

**Issue by zhangxiaodi** [Observerspy/CS294#2]
想咨询一下博主第一课产生的数据，observation和action代表什么含义。我看总有有六个实体代理，不知道在哪里可以看到每个实体代理表示问题的详细介绍。比如说action表示了哪几种动作，定义域和值域的范围是那些等等。望博主能给出详细解答。我看gym对Ant-V2就一句话Make a four-legged creature walk forward as fast as possible.   看完以后还是不懂这到底是个啥。。。。。

**Comment by Observerspy** [comment]
抱歉具体的我也没有看过哈，可能要读下源码。

发自我的 iPhone

在 2018年9月20日，16:40，GFComer <notifications@github.com<mailto:notifications@github.com>> 写道：


想咨询一下博主第一课产生的数据，observation和action代表什么含义。我看总有有六个实体代理，不知道在哪里可以看到每个实体代理表示问题的详细介绍。比如说action表示了哪几种动作，定义域和值域的范围是那些等等。望博主能给出详细解答。我看gym对Ant-V2就一句话Make a four-legged creature walk forward as fast as possible. 看完以后还是不懂这到底是个啥。。。。。

**Comment by zhangxiaodi** [comment]
哦哦，不知道博主说要读哪个源码。mujoco_py的么？还是gym里面的呀
